# Generated by Django 4.0.4 on 2022-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_user',
            name='email_adr',
            field=models.EmailField(default=0, max_length=255),
        ),
    ]
