# Generated by Django 4.0.4 on 2022-04-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_email_user_email_adr'),
    ]

    operations = [
        migrations.CreateModel(
            name='emai_l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('from_adr', models.CharField(max_length=255)),
                ('date_sent', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('r_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
