# Generated by Django 4.0.4 on 2022-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_emai_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emai_l',
            name='from_adr',
            field=models.EmailField(max_length=255),
        ),
    ]
