# Generated by Django 4.0.4 on 2022-04-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_emai_l_from_adr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emai_l',
            name='r_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.email_user'),
        ),
    ]
