# Generated by Django 4.0.4 on 2022-04-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_emai_l_r_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emai_l',
            name='r_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.email_user'),
        ),
    ]
