# Generated by Django 4.0.4 on 2022-04-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_emai_l_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emai_l',
            name='date_sent',
        ),
    ]
