# Generated by Django 4.0.4 on 2022-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_emai_l_date_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emai_l',
            old_name='field_name',
            new_name='date_time',
        ),
    ]
