# Generated by Django 4.0.4 on 2022-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_emai_l_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emai_l',
            name='content',
            field=models.TextField(),
        ),
    ]
