# Generated by Django 4.0.4 on 2022-04-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_emai_l_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('your_addr', models.EmailField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.email_user')),
            ],
        ),
    ]
